// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDx6xhDPTQxeV4dMkOb7lGZtBi-9vhzNk',
    appId: '1:705263080417:web:acd60422290c7c2342b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    authDomain: 'sonartik-a7222.firebaseapp.com',
    storageBucket: 'sonartik-a7222.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2a41STGWiGnly3c-88a66lXLlMPgrng',
    appId: '1:705263080417:android:79295da222462b4f42b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    databaseURL: 'https://sonartik-a7222-default-rtdb.firebaseio.com',
    storageBucket: 'sonartik-a7222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmN5_KnX9mo9oxCBgGBsG1PCzMAdMKfc',
    appId: '1:705263080417:ios:19b496642f236dc542b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    databaseURL: 'https://sonartik-a7222-default-rtdb.firebaseio.com',
    storageBucket: 'sonartik-a7222.appspot.com',
    iosBundleId: 'com.example.sozlukUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmN5_KnX9mo9oxCBgGBsG1PCzMAdMKfc',
    appId: '1:705263080417:ios:19b496642f236dc542b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    storageBucket: 'sonartik-a7222.appspot.com',
    iosBundleId: 'com.example.sozlukUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDx6xhDPTQxeV4dMkOb7lGZtBi-9vhzNk',
    appId: '1:705263080417:web:cce1ea575b82323642b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    authDomain: 'sonartik-a7222.firebaseapp.com',
    storageBucket: 'sonartik-a7222.appspot.com',
  );

}