// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2a41STGWiGnly3c-88a66lXLlMPgrng',
    appId: '1:705263080417:android:ca7ac5ddd98ccee042b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    databaseURL: 'https://sonartik-a7222-default-rtdb.firebaseio.com',
    storageBucket: 'sonartik-a7222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmN5_KnX9mo9oxCBgGBsG1PCzMAdMKfc',
    appId: '1:705263080417:ios:14e0ca6a462fd85a42b8a0',
    messagingSenderId: '705263080417',
    projectId: 'sonartik-a7222',
    databaseURL: 'https://sonartik-a7222-default-rtdb.firebaseio.com',
    storageBucket: 'sonartik-a7222.appspot.com',
    iosBundleId: 'com.example.notlarUygulamasi',
  );

}